export const USER_FETCH_REQUESTED = `USER_FETCH_REQUESTED`;
export const   USER_VERIFY_EMAIL = `USER_VERIFY_EMAIL`;
export const    RESET_PASSWORD_SUCCESSFUL = `RESET_PASSWORD_SUCCESSFUL`;
export const    CREATE_PASSWORD_SUCCESSFUL = `CREATE_PASSWORD_SUCCESSFUL`;
export const    ADD_ADMIN_SUCCESSFUL = `ADD_ADMIN_SUCCESSFUL`;
export const    EDIT_ADMIN_SUCCESSFUL = `EDIT_ADMIN_SUCCESSFUL`;
